import fs from 'node:fs';
import { WEIGHTS, toPascalCase, type IconPathsResult } from './common.ts';

function buildAstroIconFile(iconName: string, pathData: string) {
  return `---
import Icon from '../icon.astro';
import Path from '../path.astro';
import type { IconProps } from '../types';

type Props = IconProps;

const {
  size = 24,
  color,
  class: className,
  fill,
  ['aria-label']: ariaLabel,
  role,
  ...rest
} = Astro.props;
---
<Icon
  {...{ size, color, class: className, 'aria-label': ariaLabel, role, ...rest }}
  iconName="${iconName}"
  fill={fill}
>
  <Path d="${pathData}" fill={fill} />
</Icon>
`;
}

/**
 * Generate Astro component files per icon and weight.
 */
export function generateIconFiles(
  iconName: string,
  _style: string,
  paths: IconPathsResult,
  isIdentical: boolean,
): { files: Record<string, string> } {
  const files: Record<string, string> = {};
  const kebabCaseName = iconName.replace(/_/g, '-');

  for (const weight of WEIGHTS) {
    const regularPath = paths.regular[weight];
    const filledPath = isIdentical ? paths.regular[weight] : paths.filled[weight];

    if (!regularPath) {
      continue;
    }

    files[`${kebabCaseName}.w${weight}.astro`] = buildAstroIconFile(iconName, regularPath);

    if (filledPath) {
      files[`${kebabCaseName}-fill.w${weight}.astro`] = buildAstroIconFile(iconName, filledPath);
    }
  }

  return { files };
}

/**
 * Generate Astro export entries for a specific weight.
 */
export function generateExportFileContent(iconFiles: string[], weight: number): string {
  let exportsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from './types';

`;

  for (const iconFile of iconFiles) {
    const iconName = iconFile.replace(/\.ts$/, '');
    const componentName = toPascalCase(iconName);
    const filledComponentName = `${componentName}Fill`;

    exportsContent += `export { default as ${componentName} } from './icons/${iconName}.w${weight}.astro';\n`;
    exportsContent += `export { default as ${filledComponentName} } from './icons/${iconName}-fill.w${weight}.astro';\n`;
  }

  return exportsContent;
}

export function generateDeclarationFileContent(iconFiles: string[], _weight: number): string {
  let declarationsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from './types';

`;

  for (const iconFile of iconFiles) {
    const componentName = toPascalCase(iconFile);
    const filledComponentName = `${componentName}Fill`;

    declarationsContent += `export { default as ${componentName} } from './icon-entry';\n`;
    declarationsContent += `export { default as ${filledComponentName} } from './icon-entry';\n`;
  }

  return declarationsContent;
}

export function getIconNamesForWeight(iconsDir: string, weight: number): string[] {
  return fs
    .readdirSync(iconsDir)
    .filter((file) => file.endsWith(`.w${weight}.astro`) && !file.endsWith(`-fill.w${weight}.astro`))
    .map((file) => file.slice(0, -`.w${weight}.astro`.length))
    .sort();
}

export function getTypeExportBasePath() {
  return './types';
}
