import { WEIGHTS, generatePathDataString, toPascalCase, type IconPathsResult } from './common.ts';

type TemplateOptions = {
  createIconPath?: string;
  typeExportPath?: string;
};

export function generateIconFileContent(
  iconName: string,
  style: string,
  paths: IconPathsResult,
  isIdentical: boolean,
  options: TemplateOptions = {},
): string {
  const componentName = toPascalCase(iconName);
  const filledComponentName = `${componentName}Fill`;
  const createIconPath = options.createIconPath || '../createMaterialIcon';
  const typeExportPath = options.typeExportPath || '../types';
  const { pathDataString, metadataString } = generatePathDataString(componentName, style, paths, isIdentical);

  const regularExports = WEIGHTS.map((weight) => `/**
 * ${componentName} (Weight: ${weight}) - ${style.charAt(0).toUpperCase() + style.slice(1)} style
 * @preview ![img](data:image/svg+xml;base64,${paths.previews.regular[weight]})
 */
export const ${componentName}W${weight} = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.regular[${weight}]);`).join('\n\n');
  const filledExports = WEIGHTS.map((weight) => {
    const dataKey = isIdentical ? 'regular' : 'filled';
    const previewKey = isIdentical ? 'regular' : 'filled';
    return `/**
 * ${filledComponentName} (Weight: ${weight}) - ${style.charAt(0).toUpperCase() + style.slice(1)} style (Filled)
 * @preview ![img](data:image/svg+xml;base64,${paths.previews[previewKey][weight]})
 */
export const ${filledComponentName}W${weight} = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.${dataKey}[${weight}]);`;
  }).join('\n\n');

  return `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.
import createMaterialIcon from '${createIconPath}';
import type { MaterialSymbolsComponent } from '${typeExportPath}';

${pathDataString}${metadataString}${regularExports}

${filledExports}

export const ${componentName}Metadata = metadata;
export default ${componentName}W400 satisfies MaterialSymbolsComponent;
`;
}

/**
 * Generate Astro export entries for a specific weight.
 */
export function generateExportFileContent(iconFiles: string[], weight: number, options: TemplateOptions = {}): string {
  const typeExportPath = options.typeExportPath || './types';
  let exportsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from '${typeExportPath}';

`;

  for (const iconFile of iconFiles) {
    const iconName = iconFile.replace(/\.ts$/, '');
    const componentName = toPascalCase(iconName);
    const filledComponentName = `${componentName}Fill`;

    exportsContent += `export { ${componentName}W${weight} as ${componentName}, ${filledComponentName}W${weight} as ${filledComponentName} } from './icons/${iconName}';\n`;
  }

  return exportsContent;
}

export function getTypeExportBasePath() {
  return './types';
}
