import { WEIGHTS, generatePathDataString, toPascalCase, type IconPathsResult } from './common.ts';

type TemplateOptions = {
  createIconPath?: string;
  typeExportPath?: string;
};

function buildAstroIconModule(
  iconName: string,
  style: string,
  paths: IconPathsResult,
  isIdentical: boolean,
  options: TemplateOptions = {},
) {
  const componentName = toPascalCase(iconName);
  const filledComponentName = `${componentName}Fill`;
  const createIconPath = options.createIconPath || '../createMaterialIcon';
  const { pathDataString, metadataString } = generatePathDataString(componentName, style, paths, isIdentical);

  const regularExports = WEIGHTS.map((weight) => `export const ${componentName}W${weight} = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.regular[${weight}]);`).join('\n');
  const filledExports = WEIGHTS.map((weight) => {
    const dataKey = isIdentical ? 'regular' : 'filled';
    return `export const ${filledComponentName}W${weight} = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.${dataKey}[${weight}]);`;
  }).join('\n');

  return `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.
import createMaterialIcon from '${createIconPath}';
import type { MaterialSymbolsComponent } from '../types';

${pathDataString}${metadataString}${regularExports}

${filledExports}

export const ${componentName}Metadata = metadata;
export default ${componentName}W400 satisfies MaterialSymbolsComponent;
`;
}

function buildAstroIconDeclaration(iconName: string) {
  const componentName = toPascalCase(iconName);
  const filledComponentName = `${componentName}Fill`;
  const declarations = WEIGHTS.flatMap((weight) => [
    `export declare const ${componentName}W${weight}: MaterialSymbolsComponent;`,
    `export declare const ${filledComponentName}W${weight}: MaterialSymbolsComponent;`,
  ]).join('\n');

  return `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.
import type { MaterialSymbolsComponent } from '../types';

${declarations}

export declare const ${componentName}Metadata: Record<string, unknown>;
declare const _default: MaterialSymbolsComponent;
export default _default;
`;
}

/**
 * Generate Astro component files per icon and weight.
 */
export function generateIconFiles(
  iconName: string,
  style: string,
  paths: IconPathsResult,
  isIdentical: boolean,
  options: TemplateOptions = {},
): { files: Record<string, string> } {
  const kebabCaseName = iconName.replace(/_/g, '-');
  return {
    files: {
      [`${kebabCaseName}.ts`]: buildAstroIconModule(iconName, style, paths, isIdentical, options),
      [`${kebabCaseName}.d.ts`]: buildAstroIconDeclaration(iconName),
    }
  };
}

/**
 * Generate Astro export entries for a specific weight.
 */
export function generateExportFileContent(iconFiles: string[], weight: number): string {
  let exportsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from './types';

`;

  for (const iconFile of iconFiles) {
    const iconName = iconFile.replace(/\.ts$/, '');
    const componentName = toPascalCase(iconName);
    const filledComponentName = `${componentName}Fill`;

    exportsContent += `export { ${componentName}W${weight} as ${componentName}, ${filledComponentName}W${weight} as ${filledComponentName} } from './icons/${iconName}';\n`;
  }

  return exportsContent;
}

export function generateDeclarationFileContent(iconFiles: string[], _weight: number): string {
  let declarationsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from './types';

`;

  for (const iconFile of iconFiles) {
    const iconName = iconFile.replace(/\.ts$/, '');
    const componentName = toPascalCase(iconName);
    const filledComponentName = `${componentName}Fill`;

    declarationsContent += `export { ${componentName}W${_weight} as ${componentName}, ${filledComponentName}W${_weight} as ${filledComponentName} } from './icons/${iconName}';\n`;
  }

  return declarationsContent;
}

export function getTypeExportBasePath() {
  return './types';
}
