import { WEIGHTS, generatePathDataString, toPascalCase, type IconPathsResult } from './common.ts';

const CREATE_ICON_PATH = '../createMaterialIcon';

type TemplateOptions = {
  createIconPath?: string;
  typeExportPath?: string;
};

/**
 * Generate React icon file content
 */
export function generateIconFileContent(
  iconName: string,
  style: string,
  paths: IconPathsResult,
  isIdentical: boolean,
  options: TemplateOptions = {},
): string {
  const componentName = toPascalCase(iconName);
  const filledComponentName = `${componentName}Fill`;
  const createIconPath = options.createIconPath || CREATE_ICON_PATH;
  const typeExportPath = options.typeExportPath || createIconPath;

  const { pathDataString, metadataString } = generatePathDataString(componentName, style, paths, isIdentical);

  const regularExports = WEIGHTS.map(w => 
    `/**
 * ${componentName} (Weight: ${w}) - ${style.charAt(0).toUpperCase() + style.slice(1)} style
 * @preview ![img](data:image/svg+xml;base64,${paths.previews.regular[w]})
 */
export const ${componentName}W${w}: MaterialSymbolsComponent = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.regular[${w}]);`
  ).join('\n\n');

  const filledExports = WEIGHTS.map(w => {
    const dataKey = isIdentical ? 'regular' : 'filled';
    const previewKey = isIdentical ? 'regular' : 'filled';
    return `/**
 * ${filledComponentName} (Weight: ${w}) - ${style.charAt(0).toUpperCase() + style.slice(1)} style (Filled)
 * @preview ![img](data:image/svg+xml;base64,${paths.previews[previewKey][w]})
 */
export const ${filledComponentName}W${w}: MaterialSymbolsComponent = /*#__PURE__*/ createMaterialIcon('${iconName}', pathData.${dataKey}[${w}]);`;
  }).join('\n\n');

  return `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.
import createMaterialIcon from '${createIconPath}';
import type { MaterialSymbolsComponent } from '${typeExportPath}';

${pathDataString}${metadataString}// --- Regular ---
${regularExports}

// --- Filled ---
${filledExports}

// Export metadata for tooling
export const ${componentName}Metadata = metadata;
`;
}

/**
 * Generate React export file content for a specific weight
 */
export function generateExportFileContent(iconFiles: string[], weight: number, options: TemplateOptions = {}): string {
  const createIconPath = options.typeExportPath || options.createIconPath || './createMaterialIcon';
  let exportsContent = `/* eslint-disable */
// This file is auto-generated by build scripts.
// Do not edit this file directly.

export type { IconProps, MaterialSymbolsComponent } from '${createIconPath}';

`;

  for (const iconFile of iconFiles) {
    const iconName = iconFile.replace('.ts', '');
    const componentName = toPascalCase(iconName);
    const filledComponentName = `${componentName}Fill`;
    
    const internalName = `${componentName}W${weight}`;
    const internalFilledName = `${filledComponentName}W${weight}`;

    exportsContent += `export { ${internalName} as ${componentName}, ${internalFilledName} as ${filledComponentName} } from './icons/${iconName}';\n`;
  }

  return exportsContent;
}

export function getTypeExportBasePath() {
  return './createMaterialIcon';
}
